import test from 'node:test';import assert from 'node:assert/strict';
import {run,choose} from './scheduler.mjs';import {encryptState,decryptState} from './crypto.mjs';
const now=new Date('2026-10-07T03:02:00Z');
function fixture(){return {version:1,enabled:true,account:'plusoneapp_appcreater',rules:[{app_id:'',platform:'Threads',enabled:true,days:[2],times:['12:00'],updated_at:'2026-10-06T00:00:00Z'}],items:[{id:'one',app_id:'',platform:'Threads',position:1,state:'waiting',body:'買い物リストを作ったのに、お店で見るのを忘れる。',hashtags:'#アプリ',enqueued_at:'2026-10-06T00:00:00Z',dispatch_at:''},{id:'two',app_id:'',platform:'Threads',position:2,state:'waiting',body:'次の投稿',hashtags:'#アプリ',enqueued_at:'2026-10-06T00:00:00Z',dispatch_at:''}],ticks:{}};}
function memory(value=fixture()){let version=1,state=structuredClone(value),writes=0;return {get state(){return structuredClone(state)},get writes(){return writes},async read(){return {state:structuredClone(state),sha:String(version)}},async write(value,sha){assert.equal(sha,String(version));writes++;state=structuredClone(value);return String(++version)}};}
function publisher(){return {calls:0,async identity(expected){assert.equal(expected,'plusoneapp_appcreater')},async publish(){this.calls++;return {id:'123',url:'https://www.threads.net/@user/post/123'}}};}
test('state encryption authenticates and has no public plaintext',()=>{const key=Buffer.alloc(32,1).toString('base64'),value=fixture(),encrypted=encryptState(value,key);assert(!JSON.stringify(encrypted).includes(value.items[0].body));assert.deepEqual(decryptState(encrypted,key),value);assert.throws(()=>decryptState(encrypted,Buffer.alloc(32,2).toString('base64')));});
test('dry run verifies account but never writes or publishes',async()=>{const store=memory(),p=publisher();let checks=0;p.identity=async()=>{checks++};const result=await run(store,p,{now});assert.equal(checks,1);assert(result.account_verified);assert.equal(p.calls,0);assert.equal(store.writes,0)});
test('one recent JST tick one post and duplicate run sends none',async()=>{const store=memory(),p=publisher();assert.equal((await run(store,p,{now,dryRun:false})).sent,1);await run(store,p,{now,dryRun:false});assert.equal(p.calls,1);assert.equal(store.state.items[0].state,'sent');assert.equal(store.state.items[1].state,'waiting');});
test('timeout blocks queue and never re-sends',async()=>{const store=memory(),p=publisher();p.publish=async()=>{p.calls++;throw Error('timeout')};await run(store,p,{now,dryRun:false});await run(store,p,{now:new Date('2026-10-14T03:02:00Z'),dryRun:false});assert.equal(p.calls,1);assert.equal(store.state.items[0].state,'error')});
test('failed result commit preserves pre-POST durable marker',async()=>{const store=memory(),p=publisher(),write=store.write.bind(store);store.write=async(v,sha)=>{if(v.items[0].state==='sent')throw Error('commit timeout');return write(v,sha)};await assert.rejects(run(store,p,{now,dryRun:false}));assert.equal(store.state.items[0].state,'sending');store.write=write;await run(store,p,{now,dryRun:false});assert.equal(p.calls,1);assert.equal(store.state.items[0].state,'error')});
test('CAS race prevents publication',async()=>{const store=memory(),p=publisher();store.write=async()=>{throw Error('conflict')};await assert.rejects(run(store,p,{now,dryRun:false}));assert.equal(p.calls,0)});
test('parallel runs lose CAS before sending',async()=>{const store=memory(),p=publisher();const results=await Promise.allSettled([run(store,p,{now,dryRun:false}),run(store,p,{now,dryRun:false})]);assert.equal(results.filter(v=>v.status==='fulfilled').length,1);assert.equal(p.calls,1)});
test('stopped, cancelled, errors, other media excluded',()=>{for(const change of [v=>v.enabled=false,v=>v.rules[0].enabled=false,v=>v.items[0].state='error',v=>v.items.forEach(i=>i.state='cancelled'),v=>v.rules[0].platform='X',v=>v.rules[0].platform='Instagram']){const state=fixture();change(state);assert.equal(choose(state,now),null)}});
test('no retroactive tick, 30 minute cutoff, weekday follows JST',()=>{const state=fixture();assert.equal(choose(state,new Date('2026-10-07T03:30:00Z')),null);state.items[0].enqueued_at='2026-10-07T03:01:00Z';assert.equal(choose(state,now),null);state.items[0].enqueued_at='2026-10-06T00:00:00Z';state.rules[0].updated_at='2026-10-07T03:01:00Z';assert.equal(choose(state,now),null);const midnight=fixture();midnight.rules[0].days=[3];midnight.rules[0].times=['00:00'];assert(choose(midnight,new Date('2026-10-07T15:02:00Z')))});
test('malformed overlong body blocks instead of publishing',async()=>{const value=fixture();value.items[0].body='a'.repeat(501);const store=memory(value),p=publisher();await run(store,p,{now,dryRun:false});assert.equal(store.state.items[0].state,'error');assert.equal(p.calls,0)});
test('expired account records actionable health without consuming the queue',async()=>{const store=memory(),p=publisher();p.identity=async()=>{throw Error('expired')};const result=await run(store,p,{now,dryRun:false});assert(result.connection_error);assert.equal(p.calls,0);assert.equal(store.state.items[0].state,'waiting');assert(store.state.message.includes('接続'))});
